default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: 'application_development'
  host: 127.0.0.1
  username: root
  password:

test:
  <<: *default
  database: 'application_test'
  host: 127.0.0.1
  username: root
  password:

production:
  <<: *default
  database: 'application'
  host: 127.0.0.1
  username: root
  password:
